### ISSUE TITLE
Fix security scan issues

### ISSUE THREAD

**Issue by mkrusche** [NJCoast/cyberspatial#152]
Tim scanned the CRC VM's and collected all the vulnerabilities here: 
https://redmine.crc.nd.edu/redmine/issues/9579

- [ ] Support #9580: Exposed Web Services
- [ ] Support #9581: Campus-Exposed Services 
- [ ] Support #9582: Internet-Exposed Services
- [ ] Support #9584: Unsecured Proxy / Remote File Inclusion 
- [ ] Support #9585: Various Web Server Configuration-Related Findings 
- [ ] Support #9586: Secure Pages Include Mixed Content 	
- [ ] Support #9587: Cross-Domain JavaScript Source File Inclusion
